# Generated by Django 4.1.6 on 2023-11-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vtubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='vtuber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holo.vtubers'),
        ),
    ]
